<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PresensiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('presensis')->insert([
            [
                'id_presensi' => 1,
                'id_pegawai' => 1,
                'tanggal' => '2025-01-02',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:05:00',
                'jam_keluar' => '17:30:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 5,
                'lembur_menit' => 30,
            ],
            [
                'id_presensi' => 2,
                'id_pegawai' => 1,
                'tanggal' => '2025-01-03',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:00:00',
                'jam_keluar' => '16:50:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],
            [
                'id_presensi' => 3,
                'id_pegawai' => 1,
                'tanggal' => '2025-01-04',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:20:00',
                'jam_keluar' => '18:00:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 20,
                'lembur_menit' => 60,
            ],
            [
                'id_presensi' => 4,
                'id_pegawai' => 1,
                'tanggal' => '2025-01-05',
                'status_hadir' => 'alpa',
                'jam_masuk' => null,
                'jam_keluar' => null,
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],
            [
                'id_presensi' => 5,
                'id_pegawai' => 1,
                'tanggal' => '2025-01-06',
                'status_hadir' => 'hadir',
                'jam_masuk' => '08:50:00',
                'jam_keluar' => '17:15:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 15,
            ],

            // PEGAWAI 2
            [
                'id_presensi' => 6,
                'id_pegawai' => 2,
                'tanggal' => '2025-01-02',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:00:00',
                'jam_keluar' => '17:00:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],
            [
                'id_presensi' => 7,
                'id_pegawai' => 2,
                'tanggal' => '2025-01-03',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:10:00',
                'jam_keluar' => '17:05:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 10,
                'lembur_menit' => 5,
            ],
            [
                'id_presensi' => 8,
                'id_pegawai' => 2,
                'tanggal' => '2025-01-04',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:00:00',
                'jam_keluar' => '17:00:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],
            [
                'id_presensi' => 9,
                'id_pegawai' => 2,
                'tanggal' => '2025-01-05',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:30:00',
                'jam_keluar' => '17:10:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 30,
                'lembur_menit' => 10,
            ],
            [
                'id_presensi' => 10,
                'id_pegawai' => 2,
                'tanggal' => '2025-01-06',
                'status_hadir' => 'hadir',
                'jam_masuk' => '08:55:00',
                'jam_keluar' => '16:55:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],

            // PEGAWAI 3
            [
                'id_presensi' => 11,
                'id_pegawai' => 3,
                'tanggal' => '2025-01-02',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:00:00',
                'jam_keluar' => '19:00:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 120,
            ],
            [
                'id_presensi' => 12,
                'id_pegawai' => 3,
                'tanggal' => '2025-01-03',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:40:00',
                'jam_keluar' => '17:20:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 40,
                'lembur_menit' => 20,
            ],
            [
                'id_presensi' => 13,
                'id_pegawai' => 3,
                'tanggal' => '2025-01-04',
                'status_hadir' => 'alpa',
                'jam_masuk' => null,
                'jam_keluar' => null,
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],
            [
                'id_presensi' => 14,
                'id_pegawai' => 3,
                'tanggal' => '2025-01-05',
                'status_hadir' => 'hadir',
                'jam_masuk' => '08:55:00',
                'jam_keluar' => '17:10:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 10,
            ],

            // PEGAWAI 4
            [
                'id_presensi' => 15,
                'id_pegawai' => 4,
                'tanggal' => '2025-01-02',
                'status_hadir' => 'hadir',
                'jam_masuk' => '08:45:00',
                'jam_keluar' => '17:30:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 30,
            ],
            [
                'id_presensi' => 16,
                'id_pegawai' => 4,
                'tanggal' => '2025-01-03',
                'status_hadir' => 'hadir',
                'jam_masuk' => '08:50:00',
                'jam_keluar' => '17:00:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],
            [
                'id_presensi' => 17,
                'id_pegawai' => 4,
                'tanggal' => '2025-01-04',
                'status_hadir' => 'hadir',
                'jam_masuk' => '08:40:00',
                'jam_keluar' => '18:00:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 60,
            ],
            [
                'id_presensi' => 18,
                'id_pegawai' => 4,
                'tanggal' => '2025-01-05',
                'status_hadir' => 'hadir',
                'jam_masuk' => '08:55:00',
                'jam_keluar' => '16:50:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],

            // PEGAWAI 5
            [
                'id_presensi' => 19,
                'id_pegawai' => 5,
                'tanggal' => '2025-01-02',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:30:00',
                'jam_keluar' => '17:05:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 30,
                'lembur_menit' => 5,
            ],
            [
                'id_presensi' => 20,
                'id_pegawai' => 5,
                'tanggal' => '2025-01-03',
                'status_hadir' => 'hadir',
                'jam_masuk' => '10:00:00',
                'jam_keluar' => '17:00:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 60,
                'lembur_menit' => 0,
            ],
            [
                'id_presensi' => 21,
                'id_pegawai' => 5,
                'tanggal' => '2025-01-04',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:50:00',
                'jam_keluar' => '18:00:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 50,
                'lembur_menit' => 60,
            ],
            [
                'id_presensi' => 22,
                'id_pegawai' => 5,
                'tanggal' => '2025-01-05',
                'status_hadir' => 'alpa',
                'jam_masuk' => null,
                'jam_keluar' => null,
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 0,
                'lembur_menit' => 0,
            ],
            [
                'id_presensi' => 23,
                'id_pegawai' => 5,
                'tanggal' => '2025-01-06',
                'status_hadir' => 'hadir',
                'jam_masuk' => '09:45:00',
                'jam_keluar' => '17:10:00',
                'jam_masuk_normal' => '09:00:00',
                'jam_keluar_normal' => '17:00:00',
                'terlambat_menit' => 45,
                'lembur_menit' => 10,
            ],
        ]);
    }
}
